services:
  frontend:
    build: ./frontend
    container_name: noto-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:password@mongo:27017/noto?authSource=admin
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev

  mongo:
    image: mongo:7
    container_name: noto-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: noto
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: